name: turkticaret_net_case
description: "Project for Turk Ticaret Net Case Study"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

# -------------------------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Localization
  intl: ^0.19.0
  
  # Screen Size Control
  flutter_screenutil: ^5.9.3

  # State Management & Navigation & Localization
  get: ^4.7.2

  # Storage
  get_storage: ^2.1.1  
  
  # Auto Size Text
  auto_size_text: ^3.0.0

  # Google Fonts
  google_fonts: ^6.2.1

  # App Logo
  flutter_launcher_icons: ^0.14.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# ----------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

# App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
